In [1]:
# Import the Labraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [2]:
os.getcwd()

'c:\\Users\\HP\\Desktop\\Machine Learning Programing with prajwal'

In [3]:
# Load the Data Set

os.chdir('C:\\Users\\HP\\Downloads\\Batch 93 Day31\\')

In [4]:
df1=pd.read_csv('Social_Network_Ads.csv')
print(df1)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    11021175    Male   42           121315          0
1    17782313    Male   53            67214          0
2    14603818  Female   59           111005          0
3    18188198  Female   39            53414          0
4    19357305    Male   39           114285          0
..        ...     ...  ...              ...        ...
395  10220446  Female   20           141231          1
396  12387292    Male   50            75848          1
397  10715173  Female   25            82560          1
398  10016842    Male   55           147667          0
399  11699655  Female   54           134972          1

[400 rows x 5 columns]


In [5]:
# Independent Variable X

x=df1.iloc[:,2:4].values
print(x)

[[    42 121315]
 [    53  67214]
 [    59 111005]
 [    39  53414]
 [    39 114285]
 [    39 107458]
 [    20  85582]
 [    59 148335]
 [    48  80579]
 [    42 114204]
 [    32  87786]
 [    49 113544]
 [    55  88300]
 [    54 147066]
 [    57 139622]
 [    41 134716]
 [    51 116333]
 [    55  72567]
 [    44 123254]
 [    47 113548]
 [    52  79343]
 [    20 106149]
 [    40  59674]
 [    52  76333]
 [    28 118742]
 [    22 105897]
 [    25 114815]
 [    38  85428]
 [    57 114005]
 [    57 133402]
 [    43 106726]
 [    35  84550]
 [    34  96296]
 [    32  68964]
 [    55  90946]
 [    48  51787]
 [    22  53940]
 [    42 138928]
 [    59 116474]
 [    23  97284]
 [    40 132951]
 [    24 119308]
 [    50 120675]
 [    41 113547]
 [    52 102686]
 [    34 140262]
 [    20  54075]
 [    25  63715]
 [    46  56058]
 [    58  65052]
 [    38  72107]
 [    21 108656]
 [    42 120639]
 [    31  68033]
 [    26  80283]
 [    47  60952]
 [    31 123137]
 [    36  98529]
 [    25 12130

In [6]:
# Dependent Variable Y

y=df1.iloc[:,4].values
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [19]:
# Feature Scaling - Standardization (To standardize Salary)

from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x=sc_x.fit_transform(x)
print(x)

[[ 0.17951354  0.76103154]
 [ 1.11315372 -1.14804259]
 [ 1.622412    0.39722026]
 [-0.0751156  -1.63500628]
 [-0.0751156   0.51296235]
 [-0.0751156   0.27205647]
 [-1.68776681 -0.49988685]
 [ 1.622412    1.71449234]
 [ 0.68877182 -0.67642883]
 [ 0.17951354  0.51010409]
 [-0.66925025 -0.42211381]
 [ 0.7736482   0.48681452]
 [ 1.28290648 -0.40397617]
 [ 1.1980301   1.66971285]
 [ 1.45265924  1.40703476]
 [ 0.09463716  1.23391563]
 [ 0.94340096  0.58523059]
 [ 1.28290648 -0.95915007]
 [ 0.3492663   0.82945347]
 [ 0.60389544  0.48695567]
 [ 1.02827734 -0.72004384]
 [-1.68776681  0.2258655 ]
 [ 0.00976078 -1.41410826]
 [ 1.02827734 -0.82625839]
 [-1.00875577  0.67023751]
 [-1.51801405  0.21697311]
 [-1.26338491  0.53166458]
 [-0.15999198 -0.50532108]
 [ 1.45265924  0.50308193]
 [ 1.45265924  1.18754822]
 [ 0.26438992  0.24622622]
 [-0.41462111 -0.53630326]
 [-0.49949749 -0.12181953]
 [-0.66925025 -1.08628994]
 [ 1.28290648 -0.31060618]
 [ 0.68877182 -1.6924186 ]
 [-1.51801405 -1.6164452 ]
 

In [8]:
# Train Test Split Data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x.shape)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(400, 2)
(320, 2)
(80, 2)
(320,)
(80,)


In [9]:
# Create Model - GaussianNB

from sklearn.naive_bayes import GaussianNB
GNB=GaussianNB()
GNB.fit(x_train,y_train)
print(GNB)

GaussianNB()


In [10]:
# Predict the Result

GNB_pred=GNB.predict(x)
print(GNB_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [11]:
# Display the result in Data Frame......OK Prajwal😅

df_GNBpred=pd.DataFrame(GNB_pred,columns=['Prediction'])
result=pd.concat([df1,df_GNBpred],axis=1)
print(result)

      User ID  Gender  Age  EstimatedSalary  Purchased  Prediction
0    11021175    Male   42           121315          0           0
1    17782313    Male   53            67214          0           0
2    14603818  Female   59           111005          0           0
3    18188198  Female   39            53414          0           0
4    19357305    Male   39           114285          0           0
..        ...     ...  ...              ...        ...         ...
395  10220446  Female   20           141231          1           0
396  12387292    Male   50            75848          1           0
397  10715173  Female   25            82560          1           0
398  10016842    Male   55           147667          0           0
399  11699655  Female   54           134972          1           0

[400 rows x 6 columns]


In [12]:
# Accuracy Score to check Accuracy

from sklearn.metrics import accuracy_score
print(accuracy_score(y,GNB_pred))

0.6425


In [13]:
# Classification Report to check Accuracy

from sklearn.metrics import classification_report
print(classification_report(y,GNB_pred,zero_division=0))


              precision    recall  f1-score   support

           0       0.64      1.00      0.78       257
           1       0.00      0.00      0.00       143

    accuracy                           0.64       400
   macro avg       0.32      0.50      0.39       400
weighted avg       0.41      0.64      0.50       400



In [14]:
# Confusion Matrix to check Accuracy

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y,GNB_pred)
print(cm)

[[257   0]
 [143   0]]


In [15]:
(257+0)/400

0.6425

In [24]:
# Create Model -BernoulliNB

from sklearn.naive_bayes import BernoulliNB
BNB=BernoulliNB()
BNB.fit(x_train,y_train)
print(BNB)

BernoulliNB()


In [25]:
BNB_pred=BNB.predict(x)
print(BNB_pred)

[0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 1
 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 0 1 0 1 0 1 0 1 0 1 1 0 0 1 0 0 0 0
 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0
 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0
 0 0 0 0 1 1 1 0 1 0 0 1 0 1 1 0 0 0 0 0 1 0 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 1 0 1 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1
 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0
 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0
 0 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0]


In [22]:
df_BNBpred=pd.DataFrame(BNB_pred,columns=['Prediction'])
result=pd.concat([df1,df_BNBpred],axis=1)
print(result)

      User ID  Gender  Age  EstimatedSalary  Purchased  Prediction
0    11021175    Male   42           121315          0           0
1    17782313    Male   53            67214          0           0
2    14603818  Female   59           111005          0           0
3    18188198  Female   39            53414          0           1
4    19357305    Male   39           114285          0           0
..        ...     ...  ...              ...        ...         ...
395  10220446  Female   20           141231          1           0
396  12387292    Male   50            75848          1           0
397  10715173  Female   25            82560          1           1
398  10016842    Male   55           147667          0           0
399  11699655  Female   54           134972          1           0

[400 rows x 6 columns]


In [30]:
# Confusion matrix to check Accuracy

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y,GNB_pred)
print(cm)

[[257   0]
 [143   0]]


In [33]:
# Standardisation with Min Max Scaler - Since MultinomialNB requires all positive Numbers
x=df1.iloc[:,2:4].values
y=df1.iloc[:,4].values
from sklearn.preprocessing import MinMaxScaler
minmax_x=MinMaxScaler()
minmax_x=minmax_x.fit_transform(x)
print(minmax_x)

[[0.55       0.71613824]
 [0.825      0.17228935]
 [0.975      0.61249724]
 [0.475      0.03356521]
 [0.475      0.64546935]
 [0.475      0.57684111]
 [0.         0.35693319]
 [0.975      0.98775609]
 [0.7        0.30664066]
 [0.55       0.6446551 ]
 [0.3        0.37908884]
 [0.725      0.63802047]
 [0.875      0.38425582]
 [0.85       0.9749995 ]
 [0.925      0.90016888]
 [0.525      0.85085144]
 [0.775      0.66605682]
 [0.875      0.22610024]
 [0.6        0.73562999]
 [0.675      0.63806068]
 [0.8        0.29421581]
 [0.         0.56368242]
 [0.5        0.0964937 ]
 [0.8        0.26395786]
 [0.2        0.69027323]
 [0.05       0.5611492 ]
 [0.125      0.65079716]
 [0.45       0.35538511]
 [0.925      0.64265466]
 [0.925      0.83764249]
 [0.575      0.5694827 ]
 [0.375      0.34655904]
 [0.35       0.4646354 ]
 [0.3        0.18988118]
 [0.875      0.41085466]
 [0.7        0.01720984]
 [0.05       0.03885281]
 [0.55       0.89319246]
 [0.975      0.66747422]
 [0.075      0.47456724]


In [36]:
# Train Test Split

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(minmax_x,y,test_size=0.2 )
print(x.shape)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)


(400, 2)
(320, 2)
(80, 2)
(320,)
(80,)


In [37]:
# Create Model -MultinomialNB

from sklearn.naive_bayes import MultinomialNB
MNB=MultinomialNB()
MNB.fit(x_train,y_train)
print(MNB)

MultinomialNB()


In [38]:
MNB_pred=MNB.predict(x)
print(MNB_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [39]:
#  Accuracy Score to check Accuracy

from sklearn.metrics import accuracy_score
print(accuracy_score(y,MNB_pred))


0.6425


In [40]:
# Classification report to check the accuracy

from sklearn.metrics import classification_report
print(classification_report(y,MNB_pred,zero_division=0))

              precision    recall  f1-score   support

           0       0.64      1.00      0.78       257
           1       0.00      0.00      0.00       143

    accuracy                           0.64       400
   macro avg       0.32      0.50      0.39       400
weighted avg       0.41      0.64      0.50       400



In [42]:
# Confusion Matrix to check accuracy

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y,MNB_pred)
print(cm)

[[257   0]
 [143   0]]


In [43]:
(257+0)/400

0.6425

In [44]:
# Ok Coder Prajwal 😄